// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteNetworkWebhooksPayloadTemplateReader is a Reader for the DeleteNetworkWebhooksPayloadTemplate structure.
type DeleteNetworkWebhooksPayloadTemplateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteNetworkWebhooksPayloadTemplateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteNetworkWebhooksPayloadTemplateNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteNetworkWebhooksPayloadTemplateNoContent creates a DeleteNetworkWebhooksPayloadTemplateNoContent with default headers values
func NewDeleteNetworkWebhooksPayloadTemplateNoContent() *DeleteNetworkWebhooksPayloadTemplateNoContent {
	return &DeleteNetworkWebhooksPayloadTemplateNoContent{}
}

/*
DeleteNetworkWebhooksPayloadTemplateNoContent describes a response with status code 204, with default header values.

Successful operation
*/
type DeleteNetworkWebhooksPayloadTemplateNoContent struct {
}

// IsSuccess returns true when this delete network webhooks payload template no content response has a 2xx status code
func (o *DeleteNetworkWebhooksPayloadTemplateNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete network webhooks payload template no content response has a 3xx status code
func (o *DeleteNetworkWebhooksPayloadTemplateNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete network webhooks payload template no content response has a 4xx status code
func (o *DeleteNetworkWebhooksPayloadTemplateNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete network webhooks payload template no content response has a 5xx status code
func (o *DeleteNetworkWebhooksPayloadTemplateNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete network webhooks payload template no content response a status code equal to that given
func (o *DeleteNetworkWebhooksPayloadTemplateNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete network webhooks payload template no content response
func (o *DeleteNetworkWebhooksPayloadTemplateNoContent) Code() int {
	return 204
}

func (o *DeleteNetworkWebhooksPayloadTemplateNoContent) Error() string {
	return fmt.Sprintf("[DELETE /networks/{networkId}/webhooks/payloadTemplates/{payloadTemplateId}][%d] deleteNetworkWebhooksPayloadTemplateNoContent ", 204)
}

func (o *DeleteNetworkWebhooksPayloadTemplateNoContent) String() string {
	return fmt.Sprintf("[DELETE /networks/{networkId}/webhooks/payloadTemplates/{payloadTemplateId}][%d] deleteNetworkWebhooksPayloadTemplateNoContent ", 204)
}

func (o *DeleteNetworkWebhooksPayloadTemplateNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
