// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetNetworkClientsBandwidthUsageHistoryReader is a Reader for the GetNetworkClientsBandwidthUsageHistory structure.
type GetNetworkClientsBandwidthUsageHistoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNetworkClientsBandwidthUsageHistoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNetworkClientsBandwidthUsageHistoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetNetworkClientsBandwidthUsageHistoryOK creates a GetNetworkClientsBandwidthUsageHistoryOK with default headers values
func NewGetNetworkClientsBandwidthUsageHistoryOK() *GetNetworkClientsBandwidthUsageHistoryOK {
	return &GetNetworkClientsBandwidthUsageHistoryOK{}
}

/*
GetNetworkClientsBandwidthUsageHistoryOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetNetworkClientsBandwidthUsageHistoryOK struct {

	/* A comma-separated list of first, last, prev, and next relative links used for subsequent paginated requests.
	 */
	Link string

	Payload []interface{}
}

// IsSuccess returns true when this get network clients bandwidth usage history o k response has a 2xx status code
func (o *GetNetworkClientsBandwidthUsageHistoryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get network clients bandwidth usage history o k response has a 3xx status code
func (o *GetNetworkClientsBandwidthUsageHistoryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get network clients bandwidth usage history o k response has a 4xx status code
func (o *GetNetworkClientsBandwidthUsageHistoryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get network clients bandwidth usage history o k response has a 5xx status code
func (o *GetNetworkClientsBandwidthUsageHistoryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get network clients bandwidth usage history o k response a status code equal to that given
func (o *GetNetworkClientsBandwidthUsageHistoryOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get network clients bandwidth usage history o k response
func (o *GetNetworkClientsBandwidthUsageHistoryOK) Code() int {
	return 200
}

func (o *GetNetworkClientsBandwidthUsageHistoryOK) Error() string {
	return fmt.Sprintf("[GET /networks/{networkId}/clients/bandwidthUsageHistory][%d] getNetworkClientsBandwidthUsageHistoryOK  %+v", 200, o.Payload)
}

func (o *GetNetworkClientsBandwidthUsageHistoryOK) String() string {
	return fmt.Sprintf("[GET /networks/{networkId}/clients/bandwidthUsageHistory][%d] getNetworkClientsBandwidthUsageHistoryOK  %+v", 200, o.Payload)
}

func (o *GetNetworkClientsBandwidthUsageHistoryOK) GetPayload() []interface{} {
	return o.Payload
}

func (o *GetNetworkClientsBandwidthUsageHistoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Link
	hdrLink := response.GetHeader("Link")

	if hdrLink != "" {
		o.Link = hdrLink
	}

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
