// Code generated by go-swagger; DO NOT EDIT.

package licensing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMoveOrganizationLicensingCotermLicensesParams creates a new MoveOrganizationLicensingCotermLicensesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMoveOrganizationLicensingCotermLicensesParams() *MoveOrganizationLicensingCotermLicensesParams {
	return &MoveOrganizationLicensingCotermLicensesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMoveOrganizationLicensingCotermLicensesParamsWithTimeout creates a new MoveOrganizationLicensingCotermLicensesParams object
// with the ability to set a timeout on a request.
func NewMoveOrganizationLicensingCotermLicensesParamsWithTimeout(timeout time.Duration) *MoveOrganizationLicensingCotermLicensesParams {
	return &MoveOrganizationLicensingCotermLicensesParams{
		timeout: timeout,
	}
}

// NewMoveOrganizationLicensingCotermLicensesParamsWithContext creates a new MoveOrganizationLicensingCotermLicensesParams object
// with the ability to set a context for a request.
func NewMoveOrganizationLicensingCotermLicensesParamsWithContext(ctx context.Context) *MoveOrganizationLicensingCotermLicensesParams {
	return &MoveOrganizationLicensingCotermLicensesParams{
		Context: ctx,
	}
}

// NewMoveOrganizationLicensingCotermLicensesParamsWithHTTPClient creates a new MoveOrganizationLicensingCotermLicensesParams object
// with the ability to set a custom HTTPClient for a request.
func NewMoveOrganizationLicensingCotermLicensesParamsWithHTTPClient(client *http.Client) *MoveOrganizationLicensingCotermLicensesParams {
	return &MoveOrganizationLicensingCotermLicensesParams{
		HTTPClient: client,
	}
}

/*
MoveOrganizationLicensingCotermLicensesParams contains all the parameters to send to the API endpoint

	for the move organization licensing coterm licenses operation.

	Typically these are written to a http.Request.
*/
type MoveOrganizationLicensingCotermLicensesParams struct {

	// MoveOrganizationLicensingCotermLicenses.
	MoveOrganizationLicensingCotermLicenses MoveOrganizationLicensingCotermLicensesBody

	/* OrganizationID.

	   Organization ID
	*/
	OrganizationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the move organization licensing coterm licenses params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MoveOrganizationLicensingCotermLicensesParams) WithDefaults() *MoveOrganizationLicensingCotermLicensesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the move organization licensing coterm licenses params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MoveOrganizationLicensingCotermLicensesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the move organization licensing coterm licenses params
func (o *MoveOrganizationLicensingCotermLicensesParams) WithTimeout(timeout time.Duration) *MoveOrganizationLicensingCotermLicensesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the move organization licensing coterm licenses params
func (o *MoveOrganizationLicensingCotermLicensesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the move organization licensing coterm licenses params
func (o *MoveOrganizationLicensingCotermLicensesParams) WithContext(ctx context.Context) *MoveOrganizationLicensingCotermLicensesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the move organization licensing coterm licenses params
func (o *MoveOrganizationLicensingCotermLicensesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the move organization licensing coterm licenses params
func (o *MoveOrganizationLicensingCotermLicensesParams) WithHTTPClient(client *http.Client) *MoveOrganizationLicensingCotermLicensesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the move organization licensing coterm licenses params
func (o *MoveOrganizationLicensingCotermLicensesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMoveOrganizationLicensingCotermLicenses adds the moveOrganizationLicensingCotermLicenses to the move organization licensing coterm licenses params
func (o *MoveOrganizationLicensingCotermLicensesParams) WithMoveOrganizationLicensingCotermLicenses(moveOrganizationLicensingCotermLicenses MoveOrganizationLicensingCotermLicensesBody) *MoveOrganizationLicensingCotermLicensesParams {
	o.SetMoveOrganizationLicensingCotermLicenses(moveOrganizationLicensingCotermLicenses)
	return o
}

// SetMoveOrganizationLicensingCotermLicenses adds the moveOrganizationLicensingCotermLicenses to the move organization licensing coterm licenses params
func (o *MoveOrganizationLicensingCotermLicensesParams) SetMoveOrganizationLicensingCotermLicenses(moveOrganizationLicensingCotermLicenses MoveOrganizationLicensingCotermLicensesBody) {
	o.MoveOrganizationLicensingCotermLicenses = moveOrganizationLicensingCotermLicenses
}

// WithOrganizationID adds the organizationID to the move organization licensing coterm licenses params
func (o *MoveOrganizationLicensingCotermLicensesParams) WithOrganizationID(organizationID string) *MoveOrganizationLicensingCotermLicensesParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the move organization licensing coterm licenses params
func (o *MoveOrganizationLicensingCotermLicensesParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WriteToRequest writes these params to a swagger request
func (o *MoveOrganizationLicensingCotermLicensesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.MoveOrganizationLicensingCotermLicenses); err != nil {
		return err
	}

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
