// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteOrganizationAdaptivePolicyACLReader is a Reader for the DeleteOrganizationAdaptivePolicyACL structure.
type DeleteOrganizationAdaptivePolicyACLReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteOrganizationAdaptivePolicyACLReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteOrganizationAdaptivePolicyACLNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteOrganizationAdaptivePolicyACLNoContent creates a DeleteOrganizationAdaptivePolicyACLNoContent with default headers values
func NewDeleteOrganizationAdaptivePolicyACLNoContent() *DeleteOrganizationAdaptivePolicyACLNoContent {
	return &DeleteOrganizationAdaptivePolicyACLNoContent{}
}

/*
DeleteOrganizationAdaptivePolicyACLNoContent describes a response with status code 204, with default header values.

Successful operation
*/
type DeleteOrganizationAdaptivePolicyACLNoContent struct {
}

// IsSuccess returns true when this delete organization adaptive policy Acl no content response has a 2xx status code
func (o *DeleteOrganizationAdaptivePolicyACLNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete organization adaptive policy Acl no content response has a 3xx status code
func (o *DeleteOrganizationAdaptivePolicyACLNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete organization adaptive policy Acl no content response has a 4xx status code
func (o *DeleteOrganizationAdaptivePolicyACLNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete organization adaptive policy Acl no content response has a 5xx status code
func (o *DeleteOrganizationAdaptivePolicyACLNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete organization adaptive policy Acl no content response a status code equal to that given
func (o *DeleteOrganizationAdaptivePolicyACLNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete organization adaptive policy Acl no content response
func (o *DeleteOrganizationAdaptivePolicyACLNoContent) Code() int {
	return 204
}

func (o *DeleteOrganizationAdaptivePolicyACLNoContent) Error() string {
	return fmt.Sprintf("[DELETE /organizations/{organizationId}/adaptivePolicy/acls/{aclId}][%d] deleteOrganizationAdaptivePolicyAclNoContent ", 204)
}

func (o *DeleteOrganizationAdaptivePolicyACLNoContent) String() string {
	return fmt.Sprintf("[DELETE /organizations/{organizationId}/adaptivePolicy/acls/{aclId}][%d] deleteOrganizationAdaptivePolicyAclNoContent ", 204)
}

func (o *DeleteOrganizationAdaptivePolicyACLNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
