// Code generated by go-swagger; DO NOT EDIT.

package appliance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UpdateNetworkAppliancePrefixesDelegatedStaticReader is a Reader for the UpdateNetworkAppliancePrefixesDelegatedStatic structure.
type UpdateNetworkAppliancePrefixesDelegatedStaticReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateNetworkAppliancePrefixesDelegatedStaticReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateNetworkAppliancePrefixesDelegatedStaticOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateNetworkAppliancePrefixesDelegatedStaticOK creates a UpdateNetworkAppliancePrefixesDelegatedStaticOK with default headers values
func NewUpdateNetworkAppliancePrefixesDelegatedStaticOK() *UpdateNetworkAppliancePrefixesDelegatedStaticOK {
	return &UpdateNetworkAppliancePrefixesDelegatedStaticOK{}
}

/*
UpdateNetworkAppliancePrefixesDelegatedStaticOK describes a response with status code 200, with default header values.

Successful operation
*/
type UpdateNetworkAppliancePrefixesDelegatedStaticOK struct {
	Payload interface{}
}

// IsSuccess returns true when this update network appliance prefixes delegated static o k response has a 2xx status code
func (o *UpdateNetworkAppliancePrefixesDelegatedStaticOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update network appliance prefixes delegated static o k response has a 3xx status code
func (o *UpdateNetworkAppliancePrefixesDelegatedStaticOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update network appliance prefixes delegated static o k response has a 4xx status code
func (o *UpdateNetworkAppliancePrefixesDelegatedStaticOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update network appliance prefixes delegated static o k response has a 5xx status code
func (o *UpdateNetworkAppliancePrefixesDelegatedStaticOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update network appliance prefixes delegated static o k response a status code equal to that given
func (o *UpdateNetworkAppliancePrefixesDelegatedStaticOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update network appliance prefixes delegated static o k response
func (o *UpdateNetworkAppliancePrefixesDelegatedStaticOK) Code() int {
	return 200
}

func (o *UpdateNetworkAppliancePrefixesDelegatedStaticOK) Error() string {
	return fmt.Sprintf("[PUT /networks/{networkId}/appliance/prefixes/delegated/statics/{staticDelegatedPrefixId}][%d] updateNetworkAppliancePrefixesDelegatedStaticOK  %+v", 200, o.Payload)
}

func (o *UpdateNetworkAppliancePrefixesDelegatedStaticOK) String() string {
	return fmt.Sprintf("[PUT /networks/{networkId}/appliance/prefixes/delegated/statics/{staticDelegatedPrefixId}][%d] updateNetworkAppliancePrefixesDelegatedStaticOK  %+v", 200, o.Payload)
}

func (o *UpdateNetworkAppliancePrefixesDelegatedStaticOK) GetPayload() interface{} {
	return o.Payload
}

func (o *UpdateNetworkAppliancePrefixesDelegatedStaticOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
UpdateNetworkAppliancePrefixesDelegatedStaticBody update network appliance prefixes delegated static body
// Example: {"description":"Prefix on WAN 1 of Long Island Office network","origin":{"interfaces":["wan1"],"type":"internet"},"prefix":"2001:db8:3c4d:15::/64"}
swagger:model UpdateNetworkAppliancePrefixesDelegatedStaticBody
*/
type UpdateNetworkAppliancePrefixesDelegatedStaticBody struct {

	// A name or description for the prefix
	Description string `json:"description,omitempty"`

	// origin
	Origin *UpdateNetworkAppliancePrefixesDelegatedStaticParamsBodyOrigin `json:"origin,omitempty"`

	// A static IPv6 prefix
	Prefix string `json:"prefix,omitempty"`
}

// Validate validates this update network appliance prefixes delegated static body
func (o *UpdateNetworkAppliancePrefixesDelegatedStaticBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateOrigin(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateNetworkAppliancePrefixesDelegatedStaticBody) validateOrigin(formats strfmt.Registry) error {
	if swag.IsZero(o.Origin) { // not required
		return nil
	}

	if o.Origin != nil {
		if err := o.Origin.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("updateNetworkAppliancePrefixesDelegatedStatic" + "." + "origin")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("updateNetworkAppliancePrefixesDelegatedStatic" + "." + "origin")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this update network appliance prefixes delegated static body based on the context it is used
func (o *UpdateNetworkAppliancePrefixesDelegatedStaticBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateOrigin(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateNetworkAppliancePrefixesDelegatedStaticBody) contextValidateOrigin(ctx context.Context, formats strfmt.Registry) error {

	if o.Origin != nil {
		if err := o.Origin.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("updateNetworkAppliancePrefixesDelegatedStatic" + "." + "origin")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("updateNetworkAppliancePrefixesDelegatedStatic" + "." + "origin")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *UpdateNetworkAppliancePrefixesDelegatedStaticBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateNetworkAppliancePrefixesDelegatedStaticBody) UnmarshalBinary(b []byte) error {
	var res UpdateNetworkAppliancePrefixesDelegatedStaticBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
UpdateNetworkAppliancePrefixesDelegatedStaticParamsBodyOrigin The origin of the prefix
swagger:model UpdateNetworkAppliancePrefixesDelegatedStaticParamsBodyOrigin
*/
type UpdateNetworkAppliancePrefixesDelegatedStaticParamsBodyOrigin struct {

	// Interfaces associated with the prefix
	Interfaces []string `json:"interfaces"`

	// Type of the origin
	// Enum: [independent internet]
	Type string `json:"type,omitempty"`
}

// Validate validates this update network appliance prefixes delegated static params body origin
func (o *UpdateNetworkAppliancePrefixesDelegatedStaticParamsBodyOrigin) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var updateNetworkAppliancePrefixesDelegatedStaticParamsBodyOriginTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["independent","internet"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		updateNetworkAppliancePrefixesDelegatedStaticParamsBodyOriginTypeTypePropEnum = append(updateNetworkAppliancePrefixesDelegatedStaticParamsBodyOriginTypeTypePropEnum, v)
	}
}

const (

	// UpdateNetworkAppliancePrefixesDelegatedStaticParamsBodyOriginTypeIndependent captures enum value "independent"
	UpdateNetworkAppliancePrefixesDelegatedStaticParamsBodyOriginTypeIndependent string = "independent"

	// UpdateNetworkAppliancePrefixesDelegatedStaticParamsBodyOriginTypeInternet captures enum value "internet"
	UpdateNetworkAppliancePrefixesDelegatedStaticParamsBodyOriginTypeInternet string = "internet"
)

// prop value enum
func (o *UpdateNetworkAppliancePrefixesDelegatedStaticParamsBodyOrigin) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, updateNetworkAppliancePrefixesDelegatedStaticParamsBodyOriginTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *UpdateNetworkAppliancePrefixesDelegatedStaticParamsBodyOrigin) validateType(formats strfmt.Registry) error {
	if swag.IsZero(o.Type) { // not required
		return nil
	}

	// value enum
	if err := o.validateTypeEnum("updateNetworkAppliancePrefixesDelegatedStatic"+"."+"origin"+"."+"type", "body", o.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this update network appliance prefixes delegated static params body origin based on context it is used
func (o *UpdateNetworkAppliancePrefixesDelegatedStaticParamsBodyOrigin) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateNetworkAppliancePrefixesDelegatedStaticParamsBodyOrigin) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateNetworkAppliancePrefixesDelegatedStaticParamsBodyOrigin) UnmarshalBinary(b []byte) error {
	var res UpdateNetworkAppliancePrefixesDelegatedStaticParamsBodyOrigin
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
