// Code generated by go-swagger; DO NOT EDIT.

package switch_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetNetworkSwitchStpReader is a Reader for the GetNetworkSwitchStp structure.
type GetNetworkSwitchStpReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNetworkSwitchStpReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNetworkSwitchStpOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetNetworkSwitchStpOK creates a GetNetworkSwitchStpOK with default headers values
func NewGetNetworkSwitchStpOK() *GetNetworkSwitchStpOK {
	return &GetNetworkSwitchStpOK{}
}

/*
GetNetworkSwitchStpOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetNetworkSwitchStpOK struct {
	Payload interface{}
}

// IsSuccess returns true when this get network switch stp o k response has a 2xx status code
func (o *GetNetworkSwitchStpOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get network switch stp o k response has a 3xx status code
func (o *GetNetworkSwitchStpOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get network switch stp o k response has a 4xx status code
func (o *GetNetworkSwitchStpOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get network switch stp o k response has a 5xx status code
func (o *GetNetworkSwitchStpOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get network switch stp o k response a status code equal to that given
func (o *GetNetworkSwitchStpOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get network switch stp o k response
func (o *GetNetworkSwitchStpOK) Code() int {
	return 200
}

func (o *GetNetworkSwitchStpOK) Error() string {
	return fmt.Sprintf("[GET /networks/{networkId}/switch/stp][%d] getNetworkSwitchStpOK  %+v", 200, o.Payload)
}

func (o *GetNetworkSwitchStpOK) String() string {
	return fmt.Sprintf("[GET /networks/{networkId}/switch/stp][%d] getNetworkSwitchStpOK  %+v", 200, o.Payload)
}

func (o *GetNetworkSwitchStpOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetNetworkSwitchStpOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
