// Code generated by go-swagger; DO NOT EDIT.

package sm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetOrganizationSmVppAccountReader is a Reader for the GetOrganizationSmVppAccount structure.
type GetOrganizationSmVppAccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrganizationSmVppAccountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOrganizationSmVppAccountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetOrganizationSmVppAccountOK creates a GetOrganizationSmVppAccountOK with default headers values
func NewGetOrganizationSmVppAccountOK() *GetOrganizationSmVppAccountOK {
	return &GetOrganizationSmVppAccountOK{}
}

/*
GetOrganizationSmVppAccountOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetOrganizationSmVppAccountOK struct {
	Payload *GetOrganizationSmVppAccountOKBody
}

// IsSuccess returns true when this get organization sm vpp account o k response has a 2xx status code
func (o *GetOrganizationSmVppAccountOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get organization sm vpp account o k response has a 3xx status code
func (o *GetOrganizationSmVppAccountOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get organization sm vpp account o k response has a 4xx status code
func (o *GetOrganizationSmVppAccountOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get organization sm vpp account o k response has a 5xx status code
func (o *GetOrganizationSmVppAccountOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get organization sm vpp account o k response a status code equal to that given
func (o *GetOrganizationSmVppAccountOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get organization sm vpp account o k response
func (o *GetOrganizationSmVppAccountOK) Code() int {
	return 200
}

func (o *GetOrganizationSmVppAccountOK) Error() string {
	return fmt.Sprintf("[GET /organizations/{organizationId}/sm/vppAccounts/{vppAccountId}][%d] getOrganizationSmVppAccountOK  %+v", 200, o.Payload)
}

func (o *GetOrganizationSmVppAccountOK) String() string {
	return fmt.Sprintf("[GET /organizations/{organizationId}/sm/vppAccounts/{vppAccountId}][%d] getOrganizationSmVppAccountOK  %+v", 200, o.Payload)
}

func (o *GetOrganizationSmVppAccountOK) GetPayload() *GetOrganizationSmVppAccountOKBody {
	return o.Payload
}

func (o *GetOrganizationSmVppAccountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetOrganizationSmVppAccountOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetOrganizationSmVppAccountOKBody get organization sm vpp account o k body
swagger:model GetOrganizationSmVppAccountOKBody
*/
type GetOrganizationSmVppAccountOKBody struct {

	// The id of the VPP Account
	ID string `json:"id,omitempty"`

	// The VPP Account's Service Token
	VppServiceToken string `json:"vppServiceToken,omitempty"`
}

// Validate validates this get organization sm vpp account o k body
func (o *GetOrganizationSmVppAccountOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get organization sm vpp account o k body based on context it is used
func (o *GetOrganizationSmVppAccountOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetOrganizationSmVppAccountOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetOrganizationSmVppAccountOKBody) UnmarshalBinary(b []byte) error {
	var res GetOrganizationSmVppAccountOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
