// Code generated by go-swagger; DO NOT EDIT.

package wireless

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetOrganizationWirelessDevicesEthernetStatusesParams creates a new GetOrganizationWirelessDevicesEthernetStatusesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetOrganizationWirelessDevicesEthernetStatusesParams() *GetOrganizationWirelessDevicesEthernetStatusesParams {
	return &GetOrganizationWirelessDevicesEthernetStatusesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrganizationWirelessDevicesEthernetStatusesParamsWithTimeout creates a new GetOrganizationWirelessDevicesEthernetStatusesParams object
// with the ability to set a timeout on a request.
func NewGetOrganizationWirelessDevicesEthernetStatusesParamsWithTimeout(timeout time.Duration) *GetOrganizationWirelessDevicesEthernetStatusesParams {
	return &GetOrganizationWirelessDevicesEthernetStatusesParams{
		timeout: timeout,
	}
}

// NewGetOrganizationWirelessDevicesEthernetStatusesParamsWithContext creates a new GetOrganizationWirelessDevicesEthernetStatusesParams object
// with the ability to set a context for a request.
func NewGetOrganizationWirelessDevicesEthernetStatusesParamsWithContext(ctx context.Context) *GetOrganizationWirelessDevicesEthernetStatusesParams {
	return &GetOrganizationWirelessDevicesEthernetStatusesParams{
		Context: ctx,
	}
}

// NewGetOrganizationWirelessDevicesEthernetStatusesParamsWithHTTPClient creates a new GetOrganizationWirelessDevicesEthernetStatusesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetOrganizationWirelessDevicesEthernetStatusesParamsWithHTTPClient(client *http.Client) *GetOrganizationWirelessDevicesEthernetStatusesParams {
	return &GetOrganizationWirelessDevicesEthernetStatusesParams{
		HTTPClient: client,
	}
}

/*
GetOrganizationWirelessDevicesEthernetStatusesParams contains all the parameters to send to the API endpoint

	for the get organization wireless devices ethernet statuses operation.

	Typically these are written to a http.Request.
*/
type GetOrganizationWirelessDevicesEthernetStatusesParams struct {

	/* EndingBefore.

	   A token used by the server to indicate the end of the page. Often this is a timestamp or an ID but it is not limited to those. This parameter should not be defined by client applications. The link for the first, last, prev, or next page in the HTTP Link header should define it.
	*/
	EndingBefore *string

	/* NetworkIds.

	   A list of Meraki network IDs to filter results to contain only specified networks. E.g.: networkIds[]=N_12345678&networkIds[]=L_3456
	*/
	NetworkIds []string

	/* OrganizationID.

	   Organization ID
	*/
	OrganizationID string

	/* PerPage.

	   The number of entries per page returned. Acceptable range is 3 - 1000. Default is 100.
	*/
	PerPage *int64

	/* StartingAfter.

	   A token used by the server to indicate the start of the page. Often this is a timestamp or an ID but it is not limited to those. This parameter should not be defined by client applications. The link for the first, last, prev, or next page in the HTTP Link header should define it.
	*/
	StartingAfter *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get organization wireless devices ethernet statuses params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrganizationWirelessDevicesEthernetStatusesParams) WithDefaults() *GetOrganizationWirelessDevicesEthernetStatusesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get organization wireless devices ethernet statuses params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrganizationWirelessDevicesEthernetStatusesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get organization wireless devices ethernet statuses params
func (o *GetOrganizationWirelessDevicesEthernetStatusesParams) WithTimeout(timeout time.Duration) *GetOrganizationWirelessDevicesEthernetStatusesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get organization wireless devices ethernet statuses params
func (o *GetOrganizationWirelessDevicesEthernetStatusesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get organization wireless devices ethernet statuses params
func (o *GetOrganizationWirelessDevicesEthernetStatusesParams) WithContext(ctx context.Context) *GetOrganizationWirelessDevicesEthernetStatusesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get organization wireless devices ethernet statuses params
func (o *GetOrganizationWirelessDevicesEthernetStatusesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get organization wireless devices ethernet statuses params
func (o *GetOrganizationWirelessDevicesEthernetStatusesParams) WithHTTPClient(client *http.Client) *GetOrganizationWirelessDevicesEthernetStatusesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get organization wireless devices ethernet statuses params
func (o *GetOrganizationWirelessDevicesEthernetStatusesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEndingBefore adds the endingBefore to the get organization wireless devices ethernet statuses params
func (o *GetOrganizationWirelessDevicesEthernetStatusesParams) WithEndingBefore(endingBefore *string) *GetOrganizationWirelessDevicesEthernetStatusesParams {
	o.SetEndingBefore(endingBefore)
	return o
}

// SetEndingBefore adds the endingBefore to the get organization wireless devices ethernet statuses params
func (o *GetOrganizationWirelessDevicesEthernetStatusesParams) SetEndingBefore(endingBefore *string) {
	o.EndingBefore = endingBefore
}

// WithNetworkIds adds the networkIds to the get organization wireless devices ethernet statuses params
func (o *GetOrganizationWirelessDevicesEthernetStatusesParams) WithNetworkIds(networkIds []string) *GetOrganizationWirelessDevicesEthernetStatusesParams {
	o.SetNetworkIds(networkIds)
	return o
}

// SetNetworkIds adds the networkIds to the get organization wireless devices ethernet statuses params
func (o *GetOrganizationWirelessDevicesEthernetStatusesParams) SetNetworkIds(networkIds []string) {
	o.NetworkIds = networkIds
}

// WithOrganizationID adds the organizationID to the get organization wireless devices ethernet statuses params
func (o *GetOrganizationWirelessDevicesEthernetStatusesParams) WithOrganizationID(organizationID string) *GetOrganizationWirelessDevicesEthernetStatusesParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the get organization wireless devices ethernet statuses params
func (o *GetOrganizationWirelessDevicesEthernetStatusesParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WithPerPage adds the perPage to the get organization wireless devices ethernet statuses params
func (o *GetOrganizationWirelessDevicesEthernetStatusesParams) WithPerPage(perPage *int64) *GetOrganizationWirelessDevicesEthernetStatusesParams {
	o.SetPerPage(perPage)
	return o
}

// SetPerPage adds the perPage to the get organization wireless devices ethernet statuses params
func (o *GetOrganizationWirelessDevicesEthernetStatusesParams) SetPerPage(perPage *int64) {
	o.PerPage = perPage
}

// WithStartingAfter adds the startingAfter to the get organization wireless devices ethernet statuses params
func (o *GetOrganizationWirelessDevicesEthernetStatusesParams) WithStartingAfter(startingAfter *string) *GetOrganizationWirelessDevicesEthernetStatusesParams {
	o.SetStartingAfter(startingAfter)
	return o
}

// SetStartingAfter adds the startingAfter to the get organization wireless devices ethernet statuses params
func (o *GetOrganizationWirelessDevicesEthernetStatusesParams) SetStartingAfter(startingAfter *string) {
	o.StartingAfter = startingAfter
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrganizationWirelessDevicesEthernetStatusesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.EndingBefore != nil {

		// query param endingBefore
		var qrEndingBefore string

		if o.EndingBefore != nil {
			qrEndingBefore = *o.EndingBefore
		}
		qEndingBefore := qrEndingBefore
		if qEndingBefore != "" {

			if err := r.SetQueryParam("endingBefore", qEndingBefore); err != nil {
				return err
			}
		}
	}

	if o.NetworkIds != nil {

		// binding items for networkIds
		joinedNetworkIds := o.bindParamNetworkIds(reg)

		// query array param networkIds
		if err := r.SetQueryParam("networkIds", joinedNetworkIds...); err != nil {
			return err
		}
	}

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}

	if o.PerPage != nil {

		// query param perPage
		var qrPerPage int64

		if o.PerPage != nil {
			qrPerPage = *o.PerPage
		}
		qPerPage := swag.FormatInt64(qrPerPage)
		if qPerPage != "" {

			if err := r.SetQueryParam("perPage", qPerPage); err != nil {
				return err
			}
		}
	}

	if o.StartingAfter != nil {

		// query param startingAfter
		var qrStartingAfter string

		if o.StartingAfter != nil {
			qrStartingAfter = *o.StartingAfter
		}
		qStartingAfter := qrStartingAfter
		if qStartingAfter != "" {

			if err := r.SetQueryParam("startingAfter", qStartingAfter); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamGetOrganizationWirelessDevicesEthernetStatuses binds the parameter networkIds
func (o *GetOrganizationWirelessDevicesEthernetStatusesParams) bindParamNetworkIds(formats strfmt.Registry) []string {
	networkIdsIR := o.NetworkIds

	var networkIdsIC []string
	for _, networkIdsIIR := range networkIdsIR { // explode []string

		networkIdsIIV := networkIdsIIR // string as string
		networkIdsIC = append(networkIdsIC, networkIdsIIV)
	}

	// items.CollectionFormat: ""
	networkIdsIS := swag.JoinByFormat(networkIdsIC, "")

	return networkIdsIS
}
