// Code generated by go-swagger; DO NOT EDIT.

package wireless

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetDeviceWirelessConnectionStatsReader is a Reader for the GetDeviceWirelessConnectionStats structure.
type GetDeviceWirelessConnectionStatsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDeviceWirelessConnectionStatsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDeviceWirelessConnectionStatsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetDeviceWirelessConnectionStatsOK creates a GetDeviceWirelessConnectionStatsOK with default headers values
func NewGetDeviceWirelessConnectionStatsOK() *GetDeviceWirelessConnectionStatsOK {
	return &GetDeviceWirelessConnectionStatsOK{}
}

/*
GetDeviceWirelessConnectionStatsOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetDeviceWirelessConnectionStatsOK struct {
	Payload *GetDeviceWirelessConnectionStatsOKBody
}

// IsSuccess returns true when this get device wireless connection stats o k response has a 2xx status code
func (o *GetDeviceWirelessConnectionStatsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get device wireless connection stats o k response has a 3xx status code
func (o *GetDeviceWirelessConnectionStatsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get device wireless connection stats o k response has a 4xx status code
func (o *GetDeviceWirelessConnectionStatsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get device wireless connection stats o k response has a 5xx status code
func (o *GetDeviceWirelessConnectionStatsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get device wireless connection stats o k response a status code equal to that given
func (o *GetDeviceWirelessConnectionStatsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get device wireless connection stats o k response
func (o *GetDeviceWirelessConnectionStatsOK) Code() int {
	return 200
}

func (o *GetDeviceWirelessConnectionStatsOK) Error() string {
	return fmt.Sprintf("[GET /devices/{serial}/wireless/connectionStats][%d] getDeviceWirelessConnectionStatsOK  %+v", 200, o.Payload)
}

func (o *GetDeviceWirelessConnectionStatsOK) String() string {
	return fmt.Sprintf("[GET /devices/{serial}/wireless/connectionStats][%d] getDeviceWirelessConnectionStatsOK  %+v", 200, o.Payload)
}

func (o *GetDeviceWirelessConnectionStatsOK) GetPayload() *GetDeviceWirelessConnectionStatsOKBody {
	return o.Payload
}

func (o *GetDeviceWirelessConnectionStatsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetDeviceWirelessConnectionStatsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetDeviceWirelessConnectionStatsOKBody get device wireless connection stats o k body
swagger:model GetDeviceWirelessConnectionStatsOKBody
*/
type GetDeviceWirelessConnectionStatsOKBody struct {

	// connection stats
	ConnectionStats *GetDeviceWirelessConnectionStatsOKBodyConnectionStats `json:"connectionStats,omitempty"`

	// The serial number for the device
	Serial string `json:"serial,omitempty"`
}

// Validate validates this get device wireless connection stats o k body
func (o *GetDeviceWirelessConnectionStatsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateConnectionStats(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetDeviceWirelessConnectionStatsOKBody) validateConnectionStats(formats strfmt.Registry) error {
	if swag.IsZero(o.ConnectionStats) { // not required
		return nil
	}

	if o.ConnectionStats != nil {
		if err := o.ConnectionStats.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getDeviceWirelessConnectionStatsOK" + "." + "connectionStats")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getDeviceWirelessConnectionStatsOK" + "." + "connectionStats")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get device wireless connection stats o k body based on the context it is used
func (o *GetDeviceWirelessConnectionStatsOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateConnectionStats(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetDeviceWirelessConnectionStatsOKBody) contextValidateConnectionStats(ctx context.Context, formats strfmt.Registry) error {

	if o.ConnectionStats != nil {
		if err := o.ConnectionStats.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getDeviceWirelessConnectionStatsOK" + "." + "connectionStats")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getDeviceWirelessConnectionStatsOK" + "." + "connectionStats")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetDeviceWirelessConnectionStatsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetDeviceWirelessConnectionStatsOKBody) UnmarshalBinary(b []byte) error {
	var res GetDeviceWirelessConnectionStatsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetDeviceWirelessConnectionStatsOKBodyConnectionStats The connection stats of the device
swagger:model GetDeviceWirelessConnectionStatsOKBodyConnectionStats
*/
type GetDeviceWirelessConnectionStatsOKBodyConnectionStats struct {

	// The number of failed association attempts
	Assoc int64 `json:"assoc,omitempty"`

	// The number of failed authentication attempts
	Auth int64 `json:"auth,omitempty"`

	// The number of failed DHCP attempts
	Dhcp int64 `json:"dhcp,omitempty"`

	// The number of failed DNS attempts
	DNS int64 `json:"dns,omitempty"`

	// The number of successful connection attempts
	Success int64 `json:"success,omitempty"`
}

// Validate validates this get device wireless connection stats o k body connection stats
func (o *GetDeviceWirelessConnectionStatsOKBodyConnectionStats) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get device wireless connection stats o k body connection stats based on context it is used
func (o *GetDeviceWirelessConnectionStatsOKBodyConnectionStats) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetDeviceWirelessConnectionStatsOKBodyConnectionStats) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetDeviceWirelessConnectionStatsOKBodyConnectionStats) UnmarshalBinary(b []byte) error {
	var res GetDeviceWirelessConnectionStatsOKBodyConnectionStats
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
